version: 0.2

phase:
  install:
    runtime-version:
      java: corretto8
  pre_build:
    commands:
      - echo Pre-build completed
  build:
    commands:
      - echo Build started
      - mvn test
  post_build:
    commands:
      - echo Build completed
      - mvn package

artifacts:
  files: #이동시키고 싶은 파일들을 명시
    - target/springbootApp.jar
    - scripts/start.sh
    - scripts/stop.sh
  discard-paths: yes # 디렉토리를 무시하고 하나의 디렉토리에 위 파일을 이동.

